config/routes.rb
Rails.application.routes.draw do
  get 'buyers/index'
  get 'buyers/done'
  get 'card/new'
  get 'card/show'

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
  }

  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end

  root 'posts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  resources :posts do
    collection do
      get :search
    end
    resources :comments, only: [:create]
    resources :likes, only: [:create, :destroy]
    resources :buyers, only: [:index] do
      collection do
        get 'done', to: 'buyers#done'
        post 'pay', to: 'buyers#pay'
      end
    end
    collection do
      get 'search'
    end
  end

  resources :users, only: [:index,:show] do
    collection do
      get :likes
    end
  end

  resources :cards, only: [:new, :show, :destroy] do
    collection do
      post 'pay', to: 'cards#pay'
    end
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post 
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_post, only: [:create, :destroy]

  def create
    @like = current_user.likes.create(post_id: params[:post_id])
    @current_like = @like
  end

  def destroy
    @like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
    @like.destroy
  end

  private
  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.haml
.FavoriteRank
  .FavoriteRank__favorite
    %h2 
      お気に入り件数: 
      = @post.likes.count
      - if !user_signed_in?
        %h5 お気に入り機能使用には
        %h6 新規登録/ログインが必要です  

      - elsif current_user.already_liked?(@post)
        = link_to post_like_path(@post.id, @current_like.id), method: :delete, remote: true do
          = icon('fas', 'thumbs-up', class: "favorite-icon-color", id: "color")
        .FavoriteRank__favorite__message
          お気に入りを取り消す
      - else
        = link_to post_likes_path(@post.id), method: :post, remote: true do
          = icon('fas', 'thumbs-up', class: "favorite-icon-normal", id: "normal")
        .FavoriteRank__favorite__message
          お気に入り

app/views/likes/create.js.erb
$("<%= "#like" %>").html('<%= escape_javascript(render("likes/like", post: @post )) %>');

app/views/likes/destroy.js.erb
$("<%= "#like" %>").html('<%= escape_javascript(render("likes/like", post: @post  )) %>');