config/routes.rb
Rails.application.routes.draw do
  get 'buyers/index'
  get 'buyers/done'
  get 'card/new'
  get 'card/show'

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
  }

  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end

  root 'posts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  resources :posts do
    collection do
      get :search
    end
    resources :comments, only: [:create]
    resources :likes, only: [:create, :destroy]
    resources :buyers, only: [:index] do
      collection do
        get 'done', to: 'buyers#done'
        post 'pay', to: 'buyers#pay'
      end
    end
    collection do
      get 'search'
    end
  end

  resources :users, only: [:index,:show] do
    collection do
      get :likes
    end
  end

  resources :cards, only: [:new, :show, :destroy] do
    collection do
      post 'pay', to: 'cards#pay'
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord


  validates :name, :text, :condition, :burden, :area, :day, :price, presence: true
  validates :category , presence: true
  validates :images , presence: true, length: { maximum: 5, message: "は5枚まで投稿可能です" }


  belongs_to :user
  belongs_to :category
  has_many :images, dependent: :destroy
  has_many :comments
  accepts_nested_attributes_for :images, allow_destroy: true
  has_many :likes
  has_many :liked_users, through: :likes, source: :user


  def self.search(search)
    if search
      Post.where('name LIKE(?)', "%#{search}%")
    else
      Post.all
    end
  end


  enum condition:{
     新品、未使用:0,
     未使用に近い:1,
     目立った傷や汚れなし:2,
     やや傷や汚れあり:3,
     傷や汚れあり:4,
     全体的に状態が悪い:5
  },_suffix: true

  enum burden:{
    送料込み（出品者負担）:0,
    着払い（購入者負担）:1
  },_suffix: true

  enum area:{
     北海道:0,青森県:1,岩手県:2,宮城県:3,秋田県:4,山形県:5,福島県:6,
     茨城県:7,栃木県:8,群馬県:9,埼玉県:10,千葉県:11,東京都:12,神奈川県:13,
     新潟県:14,富山県:15,石川県:16,福井県:17,山梨県:18,長野県:19,
     岐阜県:20,静岡県:21,愛知県:22,三重県:23,
     滋賀県:24,京都府:25,大阪府:26,兵庫県:27,奈良県:28,和歌山県:29,
     鳥取県:30,島根県:31,岡山県:32,広島県:33,山口県:34,
     徳島県:35,香川県:36,愛媛県:37,高知県:38,
     福岡県:39,佐賀県:40,長崎県:41,熊本県:42,大分県:43,宮崎県:44,鹿児島県:45, 
     沖縄県:46
   },_suffix: true

   enum day:{
    "1~2日で発送":0,
    "2~3日で発送":1,
    "4~7日で発送":2
  },_suffix: true

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_parents, only: [:new, :create,:show, :edit]
  before_action :set_post, only: [:show, :destroy, :edit, :update]

  def index
    @posts = Post.includes(:images).order('created_at DESC')
  end

  def new
    @post = Post.new
    @post.images.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save!
      redirect_to root_path
    else
      render :new
    end
  end

  def search
    @posts = Post.search(params[:keyword])
    #ajax通信を開始
    respond_to do |format|
      format.html
      format.json do
        if params[:parent_id]
          @childrens = Category.find(params[:parent_id]).children
        elsif params[:children_id]
          @grandChilds = Category.find(params[:children_id]).children
        end
      end
    end
  end

  def show
    @user = @post.user
    @images = @post.images
    @comment = Comment.new
    @comments = @post.comments.includes(:user)
    @category = @post.category
    @like = Like.new
    @current_like = @post.likes.where(user_id: current_user.id).first
  end


  def destroy
    if @post.destroy
      redirect_to root_path
    else
      render :show
    end
  end

  def edit
    @post.images.new
  end

  def update
    if @post.update(post_params)
      redirect_to root_path  
    else
      render :edit
    end
  end  
  
  private
  
  def post_params
    params.require(:post).permit(:name ,:text, :condition, :burden, :category_id, :area, :day, :price, :brand, images_attributes: [:name, :_destroy, :id]).merge(user_id: current_user.id)
  end
  
  def set_parents
    @parents = Category.where(ancestry: nil)
  end

  def set_post
    @post = Post.find(params[:id])
  end 
end

app/views/posts/_Footer.html.haml
.AppBannaer
  .AppBannaer__inner
    .AppBannaer__inner__title
      だれでもかんたん、人生を変えるフリマアプリ
    .AppBannaer__inner__text
      今すぐ無料ダウンロード！
    .AppBannaer__inner__icon
      .AppBannaer__inner__icon__aBtn
        = link_to image_tag("apple.svg", class:"App_img"), "/"
      .AppBannaer__inner__icon__gBtn
        = link_to image_tag("google.svg", class:"Google_img"), "/"

.Footer
  %ul.Footer__contents
    %li.Footer__contents__content
      %h.Footer__contents__content__head 
        FURIMAについて
      %ul.Footer__contents__content__lists
        %li 
          %a.Footer__contents__content__lists__a 会社概要（運営会社）
        %li
          %a.Footer__contents__content__lists__a プライバシーポリシー
        %li 
          %a.Footer__contents__content__lists__a FURIMA利用規約
        %li 
          %a.Footer__contents__content__lists__a ポイントに関する特約
    %li.Footer__contents__content
      %h.Footer__contents__content__head
        FURIMAを見る
      %ul.Footer__contents__content__lists
        %li 
          %a.Footer__contents__content__lists__a カテゴリー一覧
        %li
          %a.Footer__contents__content__lists__a ブランド一覧
    %li.Footer__contents__content
      %h.Footer__contents__content__head
        ヘルプ＆ガイド
      %ul.Footer__contents__content__lists
        %li 
          %a.Footer__contents__content__lists__a FURIMAガイド
        %li
          %a.Footer__contents__content__lists__a FURIMAロゴ利用ガイドライン
        %li
          %a.Footer__contents__content__lists__a お知らせ
  .Footer__logo
    = link_to image_tag("Footer.png", class:"Footer_img"), "/"
    %p.Footer__logo__end
      © FURIMA

app/views/posts/_Header.html.haml
.Header
  .Header__box
    .Header__box__top
      .Header__box__top__icon
        = link_to image_tag("logo.png", class:"Header_img"), "/"
      .Header__box__top__search
        = form_with(url: search_posts_path, local: true, method: :get,) do |form|
          .Header__box__top__search__input
            = form.text_field :keyword, placeholder: "投稿を検索する", class: "SearchInput"
            .Header__box__top__search__input__icon
              %button{:type => "submit"}
                .searchBox__icon
                  = link_to image_tag("icon-search 1.png", class:"Search_img"), "/"
                  %input{name: "authenticity_token", type: "hidden"}

    .Header__box__bottom
      .Header__box__bottom__listLeft
        .Header__box__bottom__listLeft__category
          カテゴリー
        .Header__box__bottom__listLeft__brand
          ブランド
      .Header__box__bottom__listRight
        - if user_signed_in?
          .Header__box__bottom__listRight__login
            = link_to "マイページ", user_path(current_user.id)
        - else
          .Header__box__bottom__listRight__login
            = link_to "ログイン", new_user_session_path
          .Header__box__bottom__listRight__new
            = link_to "新規会員登録", new_user_registration_path

app/views/posts/_SubFooter.html.haml
.SubFooter
  = link_to "/" do
    .SubFooter__image
      = image_tag asset_path("logo.png",  size: "185x50")
  %p © FURIMA

app/views/posts/_SubHeader.html.haml
.SubHeader
  = link_to "/" do
    .SubHeader__image
      = image_tag asset_path("logo.png",  size: "185x50")

app/views/posts/index.html.haml
= render 'Header'

.Main
  .Main__visual
    .Main__visual__content
      .Main__visual__content__subtitle
        人生を変えるフリマアプリ
      .Main__visual__content__text
        FURIMAはだれでもかんたんに出品・購入できる
        %BR フリマアプリです
      .Main__visual__content__icon
        .Main__visual__content__icon__aBtn
          = link_to image_tag("apple.svg", class:"App_img"), "/"
        .Main__visual__content__icon__gBtn
          = link_to image_tag("google.svg", class:"Google_img"), "/"

  .Main__introduction
    .Main__introduction__subtitle
      FURAIMAが選ばれる3つの理由
    %ul.Main__introduction__lists
      %li.Main__introduction__lists__list
        .Main__introduction__lists__list__photo
          = link_to image_tag("pict-reason-01.jpg", class:"Reason_img"), "/"
          .Main__introduction__lists__list__photo__number
            1
        .Main__introduction__lists__list__text
          %span.ao 3分 
          ですぐに出品
        .Main__introduction__lists__list__description
          スマホで入力するだけで簡単に出品できる！
      %li.Main__introduction__lists__list
        .Main__introduction__lists__list__photo
          = link_to image_tag("pict-reason-02.jpg", class:"Reason_img"), "/"
          .Main__introduction__lists__list__photo__number
            2
        .Main__introduction__lists__list__text
          %span.ao シンプル 
          で使いやすい
        .Main__introduction__lists__list__description
          めんどくさい入力は必要なく、検索も購入もスムーズ！
      %li.Main__introduction__lists__list
        .Main__introduction__lists__list__photo
          = link_to image_tag("pict-reason-03.jpg", class:"Reason_img"), "/"
          .Main__introduction__lists__list__photo__number
            3
        .Main__introduction__lists__list__text
          手数料 
          %span.ao 業界最安
        .Main__introduction__lists__list__description
          最大3%でお得に出品&購入！

  .Main__dl
    .Main__dl__box
      .Main__dl__box__subtitle
        会員数日本一位
      .Main__dl__box__text
        FURIMAは、フリマアプリで最も人気。
        %BR 出品・購入回数も業界最多です！
        ほしかったあの商品に出会えるかもしれません。
      .Main__dl__box__icon
        .Main__dl__box__icon__aBtn
          = link_to image_tag("apple.svg", class:"App_img"), "/"
        .Main__dl__box__icon__gBtn
          = link_to image_tag("google.svg", class:"Google_img"), "/"
  .Main__features
    .Main__features__head
      FURIMAの特徴
    .Main__features__items
      .Main__features__items__item
        .Main__features__items__item__img
          = link_to image_tag("icon-01.png", class:"Features_img"), "/"
        .Main__features__items__item__subtitle
          簡単に売り買いできる
        .Main__features__items__item__detail
          スマホひとつで、いつでもどこでも簡単
          %BR に出品・購入が可能！
      .Main__features__items__item
        .Main__features__items__item__img
          = link_to image_tag("icon-02.png", class:"Features_img"), "/"
        .Main__features__items__item__subtitle
          売上金は即日振込みに対応
        .Main__features__items__item__detail
          午前9時までに振込を依頼いただけれ
          %BR ば、翌日に指定の口座に入金いたします!
      .Main__features__items__item
        .Main__features__items__item__img
          = link_to image_tag("icon-03.png", class:"Features_img"), "/"
        .Main__features__items__item__subtitle
          様々な支払いに対応
        .Main__features__items__item__detail
          お支払いは、クレジットカードだけでな
          %BR く、ポイントや売上金など多彩な方法があります。
  .Main__pickupContainer
    .Main__pickupContainer__head
      ピックアップカテゴリー
    .Main__pickupContainer__productbox
      .Main__pickupContainer__productbox__head
        新規投稿商品
      .Main__pickupContainer__productbox__lists
        - @posts.each do |post|
          .Main__pickupContainer__productbox__lists__list
            = link_to post_path(post), class:"Main__pickupContainer__productbox__lists__list__url" do
              .Main__pickupContainer__productbox__lists__list__img   
                = image_tag post.images.first.name.url, width: "600", height: '600', class: "Products_img"
                

              .Main__pickupContainer__productbox__lists__list__body
                
                .Main__pickupContainer__productbox__lists__list__body__name
                  = post.name
                .Main__pickupContainer__productbox__lists__list__body__details
                  .Main__pickupContainer__productbox__lists__list__body__details__money
                    = post.price
                    円
                  .Main__pickupContainer__productbox__lists__list__body__details__tax
                    (税金)
              -if post.buyer_id.present? 
                .items-box_photo__sold
                  .items-box_photo__sold__inner
                    SOLD

  .Main__pickupContainer
    .Main__pickupContainer__head
      ピックアップブランド
    .Main__pickupContainer__productbox
      .Main__pickupContainer__productbox__head
        アーカイバ
      .Main__pickupContainer__productbox__lists
        .Main__pickupContainer__productbox__lists__list
          .Main__pickupContainer__productbox__lists__list__img
            = link_to image_tag("Brand.jpg", class:"Products_img"), "/"
          .Main__pickupContainer__productbox__lists__list__body
            .Main__pickupContainer__productbox__lists__list__body__name
              product 1
            .Main__pickupContainer__productbox__lists__list__body__details
              .Main__pickupContainer__productbox__lists__list__body__details__money
                1000円
              .Main__pickupContainer__productbox__lists__list__body__details__tax
                (税金)
        .Main__pickupContainer__productbox__lists__list
          .Main__pickupContainer__productbox__lists__list__img
            = link_to image_tag("Brand.jpg", class:"Products_img"), "/"
          .Main__pickupContainer__productbox__lists__list__body
            .Main__pickupContainer__productbox__lists__list__body__name
              product 2
            .Main__pickupContainer__productbox__lists__list__body__details
              .Main__pickupContainer__productbox__lists__list__body__details__money
                1000円
              .Main__pickupContainer__productbox__lists__list__body__details__tax
                (税金)
        .Main__pickupContainer__productbox__lists__list
          .Main__pickupContainer__productbox__lists__list__img
            = link_to image_tag("Brand.jpg", class:"Products_img"), "/"
          .Main__pickupContainer__productbox__lists__list__body
            .Main__pickupContainer__productbox__lists__list__body__name
              product 3
            .Main__pickupContainer__productbox__lists__list__body__details
              .Main__pickupContainer__productbox__lists__list__body__details__money
                1000円
              .Main__pickupContainer__productbox__lists__list__body__details__tax
                (税金)
        .Main__pickupContainer__productbox__lists__list
          .Main__pickupContainer__productbox__lists__list__img
            = link_to image_tag("Brand.jpg", class:"Products_img"), "/"
          .Main__pickupContainer__productbox__lists__list__body
            .Main__pickupContainer__productbox__lists__list__body__name
              product 4
            .Main__pickupContainer__productbox__lists__list__body__details
              .Main__pickupContainer__productbox__lists__list__body__details__money
                1000円
              .Main__pickupContainer__productbox__lists__list__body__details__tax
                (税金)



= render 'Footer'

.PurchaseBtn
  %span.PurchaseBtn__text
    出品する
    =link_to image_tag("Camera.png", class:"Camera_img") ,new_post_path

app/views/posts/search.html.haml
=render 'Header'

.contents
  .contents__side
    = form_with model: @post, local: true do |f|
      .contents__side__box
        %p.p3 詳細検索
        .contents__side__box__box0
          .contents__side__box__box0__text
            %label.labelmessage キーワードから探す
            = f.text_field :brand , class:"contents__side__box__box0__form"
        .contents__side__box__box1
          .contents__side__box__box1__text
            %label.labelmessage カテゴリー
          #category_field
            -# = f.collection_select :category_id, @parents, :id, :name, { include_blank: "---", selected:"" }, id: "category_form", class: "contents__side__box__box1__select"
            -# = icon('fas', 'chevron-down', class: "items-btn")
        .contents__side__box__box2
          .contents__side__box__box2__text
            %label.labelmessage ブランド
          = f.text_field :brand, placeholder: "例) シャネル" , class:"contents__side__box__box2__form"
        .contents__side__box__box3
          .contents__side__box__box3__text
            %label.labelmessage 商品の状態
          = f.select :condition, Post.conditions.keys,{include_blank: "選択してください", selected:""}, {class: "contents__side__box__box3__select"}
          = icon('fas', 'chevron-down', class: "items-btn")
      .contents__side__delivery
        .contents__side__delivery__box1
          .contents__side__delivery__box1__text
            %label.labelmessage 配送料の負担
          = f.select :burden, Post.burdens.keys, {include_blank: "選択してください", selected:""}, {class: "contents__side__delivery__box1__select"}
          = icon('fas', 'chevron-down', class: "items-btn")
        .contents__side__delivery__box2
          .contents__side__delivery__box2__text
            %label.labelmessage 販売状況
          = f.select :day, Post.days.keys, {include_blank: "選択してください", selected:""}, {class: "contents__side__delivery__box2__select"}
          = icon('fas', 'chevron-down', class: "items-btn")
      .contents__side__price
        .contents__side__price__box1
          .contents__side__price__box1__text
            %p.labelmessage 販売価格
          .contents__side__price__box1__forms
            %span.money ¥
            = f.text_field :price, placeholder: "0" , class:"Post-Main__price__box1__forms__form"
      .contents__side__search
        = search_form_for @search,url: search_posts_path do |search|
          .contents__side__search__btns
            = search.submit "完了", class:"contents__side__search__btns__btn1"







  .contents__posts
  - @results.each do |post|
    .contents__posts__lists
      = link_to post_path(post), class:"Main__pickupContainer__productbox__lists__list__url" do
        .contents__posts__lists__img
          - post.images.each do |image|
            = image_tag image.name.url, class:"Products_img"

        .contents__posts__lists__body
          .contents__posts__lists__body__name
          = post.name
          .contents__posts__lists__body__details
            .contents__posts__lists__body__details__money
              = post.price
              円
            .contents__posts__lists__body__details__tax
              (税金)

=render 'Footer'

app/views/posts/show.html.haml
= render 'Header'

- breadcrumb :postshow
= render "layouts/breadcrumbs"

.Show-Main 
  .Show-Main__box
    .Show-Main__box__left
    .Show-Main__box__right
      .Show-Main__box__right__content
        .Show-Main__box__right__content__itemBox
          .Show-Main__box__right__content__itemBox__name
            = @post.name
          .Show-Main__box__right__content__itemBox__body        
            %ul.Show-Main__box__right__content__itemBox__body__lists        
              %li.Show-Main__box__right__content__itemBox__body__lists__image 
                = image_tag @images[0].name.url,class:"Main_img"                 
                %ul.Show-Main__box__right__content__itemBox__body__lists__list
                  - @images.each do |images|
                    %li.Show-Main__box__right__content__itemBox__body__lists__list__img
                      = image_tag images.name.url,class:"Sub_img"

              .Show-Main__box__right__content__itemBox__price
                .Show-Main__box__right__content__itemBox__price__name
                  = @post.price
                .Show-Main__box__right__content__itemBox__price__detail
                  .Show-Main__box__right__content__itemBox__price__detail__name
                    %p (税込)
                  .Show-Main__box__right__content__itemBox__price__detail__name
                    %p 送料込み
                    
              .Show-Main__box__right__content__itemBox__detail
                = @post.text
              .Show-Main__box__right__content__itemBox__buy
                - if user_signed_in? && current_user.card.present? && current_user.id != @post.user_id && !@post.buyer_id.present? 
                  %p= link_to '購入画面に進む',post_buyers_path(@post),class: "buy__url"

                -elsif user_signed_in? && current_user.card.blank? && current_user.id != @post.user_id
                  %p *クレジットカードが登録出来ていません*
                -else 
                  -if @post.buyer_id.present? 
                    .items-box_photo__buy
                      .items-box_photo__buy__inner
                        SOLD
                  - elsif user_signed_in?  && current_user.id == @post.user_id 
      
                  -else
                    %p 購入にはログインとカード登録が必要です。


              .Show-Main__box__right__content__itemBox__Edit
                - if user_signed_in? && current_user.id == @post.user_id && !@post.buyer_id.present? 
                  .Show-Main__box__right__content__itemBox__Edit__edit
                    %p= link_to '商品の編集', edit_post_path, method: :get, class: "buy__url"
                  .Show-Main__box__right__content__itemBox__Edit__delete
                    %p= link_to 'この商品を削除する', post_path, method: :delete, class: "delete__url"

              .Show-Main__box__right__content__itemBox__tableBox
                %table{border: 1, width: "100%",class:"table"} 
                  .Show-Main__box__right__content__itemBox__tableBox__tbody
                    %tr.Show-Main__box__right__content__itemBox__tableBox__tbody__name
                      %th.Show-Main__box__right__content__itemBox__tableBox__tbody__name__th 出品者
                      %th.Show-Main__box__right__content__itemBox__tableBox__tbody__name__td 
                        = @user.nickname

                    %tr.Show-Main__box__right__content__itemBox__tableBox__tbody__category
                      %th.Show-Main__box__right__content__itemBox__tableBox__tbody__category__th カテゴリー
                      %th.Show-Main__box__right__content__itemBox__tableBox__tbody__category__td 
                        = @category.parent.parent.name
                        %br
                        = @category.parent.name
                        %br
                        = @category.name

                    %tr.Show-Main__box__right__content__itemBox__tableBox__tbody__brand
                      %th.Show-Main__box__right__content__itemBox__tableBox__tbody__brand__th ブランド
                      %th.Show-Main__box__right__content__itemBox__tableBox__tbody__brand__td 
                        = @post.brand

                    %tr.Show-Main__box__right__content__itemBox__tableBox__tbody__condition
                      %th.Show-Main__box__right__content__itemBox__tableBox__tbody__condition__th 商品の状態
                      %th.Show-Main__box__right__content__itemBox__tableBox__tbody__condition__td 
                        = @post.condition

                    %tr.Show-Main__box__right__content__itemBox__tableBox__tbody__burden
                      %th.Show-Main__box__right__content__itemBox__tableBox__tbody__burden__th 配送料の負担
                      %th.Show-Main__box__right__content__itemBox__tableBox__tbody__burden__td 
                        = @post.burden

                    %tr.Show-Main__box__right__content__itemBox__tableBox__tbody__area
                      %th.Show-Main__box__right__content__itemBox__tableBox__tbody__area__th 発送元の地域
                      %th.Show-Main__box__right__content__itemBox__tableBox__tbody__area__td 
                        %p= link_to @post.area, "#", class: "Link__url" 

                    %tr.Show-Main__box__right__content__itemBox__tableBox__tbody__day
                      %th.Show-Main__box__right__content__itemBox__tableBox__tbody__day__th 発送日の目安
                      %th.Show-Main__box__right__content__itemBox__tableBox__tbody__day__td 
                        = @post.day

          .Show-Main__box__right__links
          %ul.Show-Main__box__right__links
            = link_to "#",class:"Link__url" do
              %li.Show-Main__box__right__links__beforeLink
                .Show-Main__box__right__links__beforeLink__img
                  = icon('fas','angle-left')
                .Show-Main__box__right__links__beforeLink__text
                  %p 前の商品
            = link_to "#",class:"Link__url" do
              %li.Show-Main__box__right__links__afterLink
                .Show-Main__box__right__links__afterLink__img
                  = icon('fas','angle-right')
                .Show-Main__box__right__links__afterLink__text
                  %p 後ろの商品
          #like.hoge
            = render 'likes/like'
        



        
      .Show-Main__box__right__content__CommentContainer
        .Show-Main__box__right__content__CommentContainer__CommentBox1
          %h4 ↓コメント一覧↓
        .Show-Main__box__right__content__CommentContainer__CommentBox__InCommentBox
          - @comments.each do |comment|
            .Show-Main__box__right__content__CommentContainer__CommentBox__InCommentBox__InComment
              .Show-Main__box__right__content__CommentContainer__CommentBox__InCommentBox__InComment__CommentsBoxes
                %img.Show-Main__box__right__content__CommentContainer__CommentBox__InCommentBox__imgIcon{alt: "", height: "40", src: "//static.mercdn.net/images/member_photo_noimage_thumb.png", width: "40"}/
                %br
                = link_to comment.user.nickname, "/users/#{comment.user_id}"
                
              .Show-Main__box__right__content__CommentContainer__CommentBox__InCommentBox__InComment__InCommentUser
                = comment.content
          
          .Show-Main__box__right__content__CommentContainer__CommentBox__CommentText
          .Show-Main__box__right__content__CommentContainer__CommentBox__CommentName  
            .Show-Main__box__right__content__CommentContainer__CommentBox__CommentName__IfCurrentUser
              - if current_user
                = form_with(model: [@post, @comment], local: true) do |form|
                  = form.text_area :content, placeholder: "入力してください", rows: "2", class:"Show-Main__box__right__content__CommentContainer__CommentBox__IfCurrentUser__UserText"
                  = form.submit "送信", class:"Show-Main__box__right__content__CommentContainer__CommentBox__IfCurrentUser__TextBtn"       
              - else
                %strong
                  %p ※※※ コメントの投稿には新規登録/ログインが必要です ※※※
      

          .Show-Main__box__right__relatedItems
            .Show-Main__box__right__relatedItems__text
              %p= link_to 'ベビー・キッズをもっと見る', "#", class: "RelatedItems__text__url" 
            .Show-Main__box__right__relatedItems__productLists
              .Show-Main__box__right__relatedItems__productLists__productList
                = link_to "#",class:"ProductList__url" do
                  .Show-Main__box__right__relatedItems__productLists__productList__img
                    = image_tag("Product.jpg", class:"ProductList_img")
                  .Show-Main__box__right__relatedItems__productLists__productList__body
                    .Show-Main__box__right__relatedItems__productLists__productList__body__name
                      %p ee
                    .Show-Main__box__right__relatedItems__productLists__productList__body__detail
                      .Show-Main__box__right__relatedItems__productLists__productList__body__detail__price
                        %p 1000円
                      .Show-Main__box__right__relatedItems__productLists__productList__body__detail__text
                        %p (税込)

= render 'Footer'